version: '3'
services: 
  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - lab-final
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    networks:
      - lab-final

volumes:
  cache:
    driver: local

networks:
  lab-final:
    driver: bridge